CREATE TABLE test_table(
    id varchar,
    name varchar,
    PRIMARY KEY(id));

INSERT INTO test_table(id, name) values('key1','Aristotle');
INSERT INTO test_table(id, name) values('key2','Dave');
INSERT INTO test_table(id, name) values('key3','Ger');
INSERT INTO test_table(id, name) values('key4','Valerio');
INSERT INTO test_table(id, name) values('key5','Stephen');
INSERT INTO test_table(id, name) values('key6','Paddy');
